### PR TITLE
fix map_long_varchar_as variable type (why isn't it a bool?)

### PR DESCRIPTION
**Pull request by finchr**
## what

Fix the map_long_varchar_as variable type. It's actually type string not a bool.

## why

The documentation implies it's a bool but it's actually a string.

## references

[AWS dms_endpoint](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/dms/endpoint.go#L2204)

### CODE REVIEW

**Comment by finchr** [comment]
Hi @joe-niland I found a bug in the last PR I submitted. Any chance for a quick turn around on this one?

**Review by joe-niland — APPROVED** [review]

**Comment by finchr** [comment]
> These changes were released in [v1.3.1](https://github.com/cloudposse/terraform-aws-dms/releases/tag/v1.3.1).

Thank you @joe-niland!

**Comment by joe-niland** [comment]
No worries @finchr - thanks for picking this up

**Pull request merged**
